### PR TITLE
#550 add new icon and connect to snippet

### PR DESCRIPTION
**Pull request by Reyka141**

### CODE REVIEW

**Comment by Reyka141** [comment]
@fey Yes, i add new icon java and connect other icon to system. 
image

**Comment by Reyka141** [comment]
image

**Comment by fey** [comment]
@Reyka141 is it works with backend? :thinking:

**Comment by Reyka141** [comment]
No, running code doesn't work with this language, I don't know how to do that.

**Comment by fey** [comment]
@Reyka141 how about creating snippets? Can you please deploy app with changes to demonstrate new feature?

**Comment by Reyka141** [comment]
For deployment I need to create a database, but I don't know how to do that, you can just check for yourself

**Comment by Reyka141** [comment]
@fey

**Comment by fey** [comment]
@Reyka141 try to deploy via instruciton from readme https://github.com/hexlet-rus/runit?tab=readme-ov-file#deploy-to-rendercom
If you have and questions, you can ask help in tg community https://t.me/hexletcommunity/12

**Pull request merged**
