### PR TITLE
[#549]: Correction of translation of the "Confirm" button when switching to English

### PR DESCRIPTION
**Pull request by PavelKochetkov**
Added translation of the "Confirm" button in the form for duplicating the snippet when switching to English

### CODE REVIEW

**Comment by fey** [comment]
@PavelKochetkov hi, you have changes of another PR. Can you rebase the branch?

**Comment by PavelKochetkov** [comment]
@fey Hi, I'm sorry, I didn't quite understand what it means to rebase a branch?

**Comment by fey** [comment]
@PavelKochetkov @PavelKochetkov you need to redit commits history. Remove commits and changes from another PR.
Your PR should contain only changes only for one issue. 
Try to practice with rebase https://git-scm.com/docs/git-rebase

**Comment by PavelKochetkov** [comment]
@fey I get it, I need to remove this commit 289177e, which is related to the logo, from this pull request we're in now?

**Comment by fey** [comment]
@PavelKochetkov yea.

**Comment by PavelKochetkov** [comment]
@fey Ok, I will do it

**Comment by fey** [comment]
@PavelKochetkov you still have another changes.

**Comment by PavelKochetkov** [comment]
@fey 
Thanks for your feedback. I thought I had it fixed. I'll see what's wrong.

**Comment by PavelKochetkov** [comment]
@fey  look, I think I fixed it

**Review by sergiozeppo — APPROVED** [review]

**Comment by fey** [comment]
good 
image

**Pull request merged**
